### ISSUE TITLE
Trouble with getting dependencies installed

### ISSUE THREAD

**Issue by jw762** [NightRang3r/P4wnP1_ALOA_LCD_MENU#1]
Like the title says, I'm having trouble with getting the dependencies to install. Been fighting with getting a p4wnp1 working with either a WaveShare 1.3 LCD hat or their 1.44 LCD hat for a while now. Surprisingly isn't a whole lot of current into on this.
Errors (shortened some so to not input so much info here): 

```
Errors were encountered while processing:
 python3-more-itertools
 python3-jaraco.classes
 python3-jaraco.functools
 python3-itsdangerous
 python3-zipp
 dhcpcd-base
 python3-typing-extensions
 python3-keyrings.alt
 python3-keyring
 iodine
 dbus-system-bus-common
 python3-asgiref
 python3-blinker
 python3-importlib-metadata
 python3-importlib-resources
 python3-flask
 python3-click
 dbus
 dhcpcd
 avahi-daemon
 libpam-systemd:armel
 dhcpcd5
 dbus-user-session
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
And for each one of those packages is an error like this: 
```
dpkg: error processing package python3-jaraco.classes (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-jaraco.functools:
 python3-jaraco.functools depends on python3-more-itertools; however:
  Package python3-more-itertools is not configured yet.
```
Some have errors like this: 
```
Setting up python3-more-itertools (10.3.0-1) ...
  File "/usr/lib/python3/dist-packages/more_itertools/recipes.py", line 885
    yield (i := seq_index(value, i + 1, stop))
             ^
SyntaxError: invalid syntax

dpkg: error processing package python3-more-itertools (--configure):
 installed python3-more-itertools package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of python3-jaraco.classes:
 python3-jaraco.classes depends on python3-more-itertools; however:
  Package python3-more-itertools is not configured yet.
```

I know it's a long shot of getting any help here, but it would be appreciated.

**Comment by NightRang3r** [comment]
@jw762 I've created several images using a newer Kali Linux version, and most (if not all) of the required libraries and dependencies are already installed.

[https://github.com/NightRang3r/P4wnP1-A.L.O.A.-Payloads](https://github.com/NightRang3r/P4wnP1-A.L.O.A.-Payloads)

**Comment by jw762** [comment]
Thank you for the response and directing me towards that. I'll take a look and see if it'll work better.

**Comment by jw762** [comment]
@NightRang3r I have the newer image flashed, but I can't seem to get it connected to the net to download anything. Never could get any of the p4wnp1's to work with passthrough net on PC (Win10). So I usually connect to PC via USB to SSH into it, but then use WiFi to connect it to the net. But now this isn't working. raspi-config's wifi settings gives a wpa_supplicant error. I also have used the following method before: 
```
sudo ip link set wlan0 down
sudo ip link set wlan0 up
sudo wpa_supplicant -B -iwlan0 -c /etc/wpa_supplicant.conf -Dnl80211,wext
sudo dhclient wlan0
```
However, when I do that on this newer image it gives me the error "sudo: dhclient: command not found" - And I can verify dhclient is not installed. And of course can't install it without internet. 

Hopefully I gave enough info for troubleshooting, and I hate to keep bugging you about it. Thank you.

**Comment by NightRang3r** [comment]
@jw762 Not sure what's going on, but it should be relatively straightforward. You connect your device via USB and SSH, and then set up the WiFi connection in client mode to gain internet access.

**Comment by jw762** [comment]
@NightRang3r Just wanted to let you know I managed to get it all working, thank you for helping and also thank you for the awesome software. The internet thing was my own fault for not properly understanding the interface and how it worked. I'm fairly new to the whole DIY hardware tools for pentesting field.
